//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pc_dcsWatcher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pc_dcsWatcher.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception rose from main thread..
        /// </summary>
        internal static string AppThreadExpMsg {
            get {
                return ResourceManager.GetString("AppThreadExpMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it okay to stop monitoring PC-DCS?.
        /// </summary>
        internal static string ExitMsg {
            get {
                return ResourceManager.GetString("ExitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending Program.
        /// </summary>
        internal static string ExitTitle {
            get {
                return ResourceManager.GetString("ExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Happened.
        /// </summary>
        internal static string ExpErrMsg1 {
            get {
                return ResourceManager.GetString("ExpErrMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Error Message].
        /// </summary>
        internal static string ExpErrMsg2 {
            get {
                return ResourceManager.GetString("ExpErrMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Error Information].
        /// </summary>
        internal static string ExpErrMsg3 {
            get {
                return ResourceManager.GetString("ExpErrMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Handling Error.
        /// </summary>
        internal static string ExpErrTitle {
            get {
                return ResourceManager.GetString("ExpErrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is already running..
        /// </summary>
        internal static string MultiStartErrMsg {
            get {
                return ResourceManager.GetString("MultiStartErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Error.
        /// </summary>
        internal static string MultiStartErrTitle {
            get {
                return ResourceManager.GetString("MultiStartErrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception rose from sub threads..
        /// </summary>
        internal static string UnhandledExpMsg {
            get {
                return ResourceManager.GetString("UnhandledExpMsg", resourceCulture);
            }
        }
    }
}
